# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='staffs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.School', verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('graduated', '已毕业'), ('dropoff', '已退学')], default='unregistered', max_length=64, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='record',
            field=models.CharField(choices=[('checked', '已签到'), ('late', '迟到'), ('absence', '缺课'), ('leave_early', '早退')], default='checked', max_length=32, verbose_name='上课记录'),
        ),
    ]
