# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20161105_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_customer_list', '可以查看客户列表'), ('view_customer_info', '可以查看客户详细信息'), ('edit_own_customer_info', '可以修改自己的客户信息'))},
        ),
    ]
