# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20161105_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_customer_list', '可以查看客户列表'), ('view_customer_info', '可以查看客户详细信息'), ('edit_own_customer_info', '可以修改自己的客户信息'), ('batch_own_customer_info', '可以批量操作自己的客户信息'), ('add_customer_info', '可以新增客户信息'), ('view_courserecord_list', '可以查看开课记录列表'), ('batch_own_courserecord_info', '可以批量操作自己的开课记录'), ('add_courserecord_info', '可以新增开课记录'), ('view_classlist_list', '可以查看班级列表'), ('edit_classlist_info', '可以修改班级'), ('batch_own_classlist_info', '可以批量操作班级'), ('add_classlist_info', '可以新增班级'), ('view_studyrecord_list', '可以查看学习记录列表'), ('edit_studyrecord_info', '可以修改学习记录'), ('batch_studyrecord_info', '可以批量操作学习记录'), ('add_studyrecord_info', '可以新增学习记录'), ('view_userprofile_list', '可以查看用户列表'), ('view_school_list', '可以查看校区列表'))},
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('signed', '已报名'), ('unregistered', '未报名'), ('graduated', '已毕业'), ('dropoff', '已退学')], default='unregistered', max_length=64, verbose_name='客户状态'),
        ),
    ]
